### ISSUE TITLE
Flatpak version using 5 times more CPU than deb version

### ISSUE THREAD

**Issue by Asghwor** [flathub/com.carpeludum.KegaFusion#1]
When playing a Mega Drive game, the Flatpak version uses 100% of one CPU:

![image](https://user-images.githubusercontent.com/30949004/158066266-64a42e3e-2567-47a0-b521-4e4f25dc5f0b.png)

while the deb version uses only between 16% and 20% of one CPU:

![image](https://user-images.githubusercontent.com/30949004/158066409-4c39875d-c933-43b5-9e32-74a87ad0f7c2.png)

Could this be a Flatpak problem or a dependency problem?

## System information:

- **OS**: Linux Mint 20.3 Cinnamon
- **GPU**: NVIDIA GeForce GTX 1660 Ti Mobile, with nvidia-driver-510
- **Kernel**: 5.4.0-104-generic

**Comment by hadess** [comment]
Should be fixed with the next build, thanks!

**Comment by pizzadude** [comment]
Note you'll have to delete ~/.var/app/com.carpeludum.KegaFusion/config/.Kega\ Fusion/Fusion.ini and then start Kega Fusion again for the fix to apply.

**Comment by hadess** [comment]
> Note you'll have to delete ~/.var/app/com.carpeludum.KegaFusion/config/.Kega\ Fusion/Fusion.ini and then start Kega Fusion again for the fix to apply.

Sigh, unfortunately, yes. Thanks for catching that.
