### ISSUE TITLE
Please add plugins like the AUR version

### ISSUE THREAD

**Issue by Ma5t3rful** [flathub/com.carpeludum.KegaFusion#2]
The plugins allows us to upscale/filter to achieve better quality. On the website there is this package which also contains plugins:

[Kega Fusion 3.63x Linux Debian/Ubuntu Package with Plugins](https://www.carpeludum.com/download/kega-fusion_3.63-2_i386.deb)

Thanks

**Comment by hadess** [comment]
The plugins are installed `/app/lib/KegaFusion/Plugins/`, and we (try to) create links for them. But I can't find how to override Kega Fusion's hardcoded paths from `~/.Kega Fusion/Plugins`.

I had to use `upx` to decompress the binary, but couldn't figure out how it opened the plugins directory (no sources...).

I'll try again after asking around a bit.
